work_dir: ./work_dir/ntu120/xsub/dev_ctr_sa1_da_fixed_aff_lsce_jm
num_worker: 8
# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: data3/ntu120/NTU120_CSub.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: True
  bone: False

test_feeder_args:
  data_path: data3/ntu120/NTU120_CSub.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: True
  bone: False
  debug: False

# model
model: model.dev_ctr_sa1_da_aff.Model
loss: label_smooth_cross_entropy
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [35, 55, 85]
warm_up_epoch: 5

# training
device: [4]  # 32651
batch_size: 64  # 14903MiB
test_batch_size: 64
num_epoch: 100
nesterov: True
# fixed是固定sa1,da的权重为1

# nohup python main.py --config config/nturgbd120-cross-subject/dev_ctr_sa1_da_fixed_aff_lsce_jm.yaml  > config/log/dev_ctr_sa1_da_fixed_aff_lsce_jm.log  2>&1
# python main.py --config config/nturgbd120-cross-subject/devctr_aff_b.yaml
# nohup python main.py --config config/nturgbd120-cross-subject/ctr_joint.yaml  --weights work_dir/ntu120/xsub/ctrgcn_joint > config/log/ctr_joint.log