work_dir: ./work_dir/ntu120/xsub/sectrgcn_j
num_worker: 8
# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: data/ntu120/NTU120_CSub.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args:
  data_path: data/ntu120/NTU120_CSub.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False

# model
model: model.sectrgcn.Model
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [35, 55]
warm_up_epoch: 5

# training
device: [0]
batch_size: 64
test_batch_size: 64
num_epoch: 100
nesterov: True
# 因为sectrgcn.py 242行有一个.cuda()这个会调用gpu 0 所以会使用gpu0的一部分显存，所以最好直接使用gpu 0 
# nohup python main.py --config config/nturgbd120-cross-subject/sectr_j.yaml  > config/log/sectr_j.log
# nohup python main.py --config config/nturgbd120-cross-subject/ctr_joint.yaml  --weights work_dir/ntu120/xsub/ctrgcn_joint > config/log/ctr_joint.log