# feeder
work_dir: ./work_dir/ucla/dev_ctr_sa1_da_fixed_aff_lsce_b
num_worker: 8
# feeders/ucla给定了数据的目录，所以这里只需要设置下什么模态，比如data_path joint motion,joint
# data_dir决定哪个data data1, data2
feeder: feeders.feeder_ucla.Feeder
train_feeder_args:
  data_dir: data
  data_path: bone
  label_path: train
  debug: False
  random_choose: True
  random_shift: False
  random_move: False
  window_size: 52
  normalization: False
  repeat: 5

test_feeder_args:
  data_dir: data
  data_path: bone
  label_path: val
  debug: False


# model
model: model.dev_ctr_sa1_da_aff.Model
loss: label_smooth_cross_entropy
model_args:
  num_class: 10
  num_point: 20
  num_person: 1
  graph: graph.ucla.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
lr_decay_rate: 0.1
step: [50]

# training
device: [1]
batch_size: 16
test_batch_size: 64
num_epoch: 100
nesterov: True
warm_up_epoch: 5
# nohup python main.py --config config/ucla/dev_ctr_sa1_da_fixed_aff_lsce_b.yaml  > config/log/1.log  2>&1
